// This file is auto-generated by scratch/combine_data.cjs
// Contains KMIT Exams Notifications, Timetables, Online Links, and Certificate Services data.

export const notifications = [
  {
    "title": "KR24 - B.Tech 4-2 REGULAR EXAM FEE NOTIFICATION MAY_JUNE 2026",
    "url": "/examination/notifications/KR24 - B.Tech (4-2) REGULAR EXAM FEE NOTIFICATION MAY_JUNE 2026.pdf",
    "date": "06-04-2026"
  },
  {
    "title": "KR23 - B.Tech 3-2 REGULAR EXAM FEE PAYMENT NOTIFICATION - JUNE 2026",
    "url": "/examination/notifications/KR23 - B.Tech (3-2) REGULAR EXAM FEE PAYMENT NOTIFICATION - JUNE 2026.pdf",
    "date": "04-04-2026"
  },
  {
    "title": "KR24 - B.TECH 1-1 LIST OF LAB INTERNALS FAILURE STUDENTS",
    "url": "/examination/notifications/KR24 - B.TECH 1 - 1 LIST OF LAB INTERNALS FAILURE STUDENTS.pdf",
    "date": "24-01-2026"
  },
  {
    "title": "KR25 - B.TECH 1-1 REGULAR EXAM FEE PAYMENT NOTIFICATION FEB 2026",
    "url": "/examination/notifications/KR25 - B.TECH 1-1 REGULAR EXAM FEE PAYMENT NOTIFICATION FEB 2026.pdf",
    "date": "18-12-2025"
  },
  {
    "title": "DETENTION LETTER FOR KR23 & KR24 REGULATIONS STUDENTS",
    "url": "/examination/notifications/DETENTION LETTER FOR KR23 & KR24 REGULATIONS STUDENTS.pdf",
    "date": "25-09-2025"
  }
];

export const timetables = [
  {
    "title": "KR24 - B.Tech 4-2 REGULAR EXAMS TIME TABLE - MAY 2026",
    "url": "/examination/notifications/KR24 - B.Tech (4-2) REGULAR EXAMS TIME TABLE - MAY 2026.pdf",
    "date": "06-04-2026"
  },
  {
    "title": "KR23 - B.Tech 3-2 REGULAR EXAMS TIME TABLE - MAY 2026",
    "url": "/examination/notifications/KR23 - B.Tech (3-2) REGULAR EXAMS TIME TABLE - MAY 2026.pdf",
    "date": "04-04-2026"
  },
  {
    "title": "KR24 - B.TECH 2-1 REGULAR EXAMS TIME TABLE - JAN 2026",
    "url": "/examination/notifications/KR24 - B.TECH 2-1 REGULAR EXAMS TIME TABLE - JAN 2026.pdf",
    "date": "13-11-2025"
  },
  {
    "title": "KR25 - B.TECH 1-1 REGULAR EXAMS TIME TABLE - FEB 2026",
    "url": "/examination/notifications/KR25 - B.TECH 1-1 REGULAR EXAMS TIME TABLE - FEB 2026.pdf",
    "date": "18-12-2025"
  }
];

export const fallbackResults = [
  {
    "title": "B.Tech 4-1 (R22) Regular & Supply Results - March 2026",
    "url": "/examination/results/B.Tech_4-1_R22_Results_Mar2026.pdf",
    "date": "10-04-2026"
  },
  {
    "title": "B.Tech 3-1 (R23) Regular Results - March 2026",
    "url": "/examination/results/B.Tech_3-1_R23_Results_Mar2026.pdf",
    "date": "08-04-2026"
  }
];

export const onlineLinks = [
  {
    "title": "JNTUH Official Student Services Portal",
    "url": "https://studentservices.jntuh.ac.in/",
    "date": "10-01-2026"
  },
  {
    "title": "KMIT Genesis Student Portal",
    "url": "https://kmit.in/genesis",
    "date": "15-01-2026"
  },
  {
    "title": "JNTUH Online Registrations Portal",
    "url": "https://registrations.jntuh.ac.in/",
    "date": "18-01-2026"
  },
  {
    "title": "National Academic Depository (NAD) Portal",
    "url": "https://nad.ndl.gov.in/",
    "date": "20-01-2026"
  }
];

export const services = {
  "offline": [
    {
      "sNo": "1",
      "name": "Duplicate Marks Memo / Duplicate CMM",
      "docs": "Studying Candidates: a) Filled in Form-1. Course Completed Candidates: a) Request letter from the candidate along with the Self Affidavit (Form-1A) on Rs.20/- Bond paper. b) Photostat copies of SSC & Aadhaar Card. c) Softcopy of passport size photograph in CD.",
      "amount": "Rs. 200/-",
      "downloads": [
        {
          "url": "formdownloads/Form-1.pdf",
          "label": "Form-1"
        },
        {
          "url": "formdownloads/Form-1A.pdf",
          "label": "Form-1A"
        }
      ]
    },
    {
      "sNo": "2",
      "name": "Original Degree Certificate(Passed out candidates before 2002)",
      "docs": "a) Filled in Form-2. b) Photostat copy of PC. c) Photostat copies of SSC & Aadhaar Card. d) Softcopy of passport size photograph in CD or DVD.",
      "amount": "Rs. 600/- + Late fee of Rs. 500/- per year",
      "downloads": [
        {
          "url": "formdownloads/Form-2.pdf",
          "label": "Form-2"
        }
      ]
    },
    {
      "sNo": "3",
      "name": "Duplicate Degree Certificate",
      "docs": "a) Filled in Form-2A. b) Original copy of Police Report stating the original degree certificate is not traced. c) Affidavit (Form-2A) on Rs.20/- Bond paper signed by First Class Magistrate. d) Photostat copy of PC/OD Certificate. e) Photostat copies of SSC & Aadhaar Card. f) Softcopy of passport size photograph in CD or DVD.",
      "amount": "Rs. 5500/-",
      "downloads": [
        {
          "url": "formdownloads/Form-2A.pdf",
          "label": "Form-2A"
        }
      ]
    },
    {
      "sNo": "4",
      "name": "Name and /or Father Name and/or Gender correction in Original Degree certificate",
      "docs": "a) Filled in Form-3. b) Request letter from the student along with address. c) Original Degree Certificate. d) Original Provisional Certificate. e) Photostat copies of SSC & Aadhaar Card. f) Softcopy of passport size photograph in CD or DVD.",
      "amount": "Rs. 500/-",
      "downloads": [
        {
          "url": "formdownloads/Form-3.pdf",
          "label": "Form-3"
        }
      ]
    },
    {
      "sNo": "5",
      "name": "Name and /or Father Name and/or Gender correction in PC",
      "docs": "Permitted only if the convocation is not held a) Filled in Form-3 b) Request letter from the student. c) Original PC. d) Photostat copies of SSC & Aadhaar Card.",
      "amount": "Rs. 250/-",
      "downloads": [
        {
          "url": "formdownloads/Form-3 (1).pdf",
          "label": "Form-3"
        }
      ]
    },
    {
      "sNo": "6",
      "name": "Name Corrections in Marks Memo/CMM",
      "docs": "a) Filled in Form-3. b) Request letter from the student. c) Original Mark Memo/CMM. d) Photostat copies of SSC & Aadhaar Card. e) Softcopy of passport size photograph in CD or DVD.",
      "amount": "Rs. 50/- per each memo",
      "downloads": [
        {
          "url": "formdownloads/Form-3 (2).pdf",
          "label": "Form-3"
        }
      ]
    },
    {
      "sNo": "7",
      "name": "Transcripts B.Tech (Admitted after 1999). M.Tech, MBA, MCA, B.Phamay, M.Pharm (Admitted after 2009)",
      "docs": "a) Filled in Form-4",
      "amount": "Rs. 60/- per each copy",
      "downloads": [
        {
          "url": "formdownloads/Form-4.pdf",
          "label": "Form-4"
        }
      ]
    },
    {
      "sNo": "8",
      "name": "Transcripts B.Tech (Admitted before 1999). M.Tech, MBA, MCA, M.Pharm, B.Phamay (Admitted before 2009)",
      "docs": "a) Filled in Form-4 b) Photostat copy of OD/PC/CMM/Marks memo, signed (on bottom left-side) by the Principal on each copy along with stamp.",
      "amount": "Rs. 60/- per each copy",
      "downloads": [
        {
          "url": "formdownloads/Form-4 (1).pdf",
          "label": "Form-4"
        }
      ]
    },
    {
      "sNo": "9",
      "name": "PC and CMM With Grace Marks",
      "docs": "a) Filled in Form-5. b) Photostat copy of SSC. c) Original Marks Memo(s) containing subject(s) for which award of Grace Marks requested.",
      "amount": "Paid at college",
      "downloads": [
        {
          "url": "formdownloads/Form-5.pdf",
          "label": "Form-5"
        }
      ]
    },
    {
      "sNo": "10",
      "name": "PC and CMM With Undertaking",
      "docs": "a) Filled in form-6 b) Photostat copy of SSC",
      "amount": "Paid at college",
      "downloads": [
        {
          "url": "formdownloads/Form-6.pdf",
          "label": "Form-6"
        }
      ]
    },
    {
      "sNo": "11",
      "name": "PC and CMM With Grace Marks and Undertaking",
      "docs": "a) Filled in form-7 b) Photostat copy of SSC c) Original Marks Memo(s) containing subject(s) for which award of Grace Marks requested.",
      "amount": "Paid at college",
      "downloads": [
        {
          "url": "formdownloads/Form-7.pdf",
          "label": "Form-7"
        }
      ]
    }
  ],
  "tatkal": [
    {
      "sNo": "1",
      "name": "Tatkal PC and CMM of B.Tech/B.Pharmacy/ M. Tech/M. Pharmacy/ Pharm D/MBA/ MCA/ M. Sc",
      "docs": "a) Filled in Form-8. b) Endorsement from the college Principal on the filled-in application form. c) Photostat copy of SSC. d) Original Project Viva Voce report (in a sealed cover) for PG courses.",
      "amount": "UG-Rs. 2000/- / PG- Rs.2210/-",
      "downloads": [
        {
          "url": "formdownloads/Form-8.pdf",
          "label": "Form-8"
        }
      ]
    },
    {
      "sNo": "2",
      "name": "Tatkal PC and CMM with Undertaking for B.Tech.",
      "docs": "a) Filled in Form-9. b) Endorsement from the college Principal on the filled-in application form. c) Photostat copy of SSC.",
      "amount": "Rs.2000/-",
      "downloads": [
        {
          "url": "formdownloads/Form-9.pdf",
          "label": "Form-9"
        }
      ]
    },
    {
      "sNo": "3",
      "name": "Tatkal Duplicate Marks Memo / Duplicate CMM",
      "docs": "Studying Candidates: a) Filled in Form-10. b) Endorsement from the college Principal on the filled-in application form. c) Photostat copies of SSC & Aadhaar Card. Course Completed Candidates: a) Request letter from the candidate along with the Self Affidavit (Form-1A) on Rs.20/- Bond paper. b) Photostat copies of SSC & Aadhaar Card. c) Softcopy of passport size photograph in CD.",
      "amount": "Rs.1200/- x No.of Memos",
      "downloads": [
        {
          "url": "formdownloads/Form-10.pdf",
          "label": "Form-10"
        },
        {
          "url": "formdownloads/Form-1A(1).pdf",
          "label": "Form-1A"
        }
      ]
    },
    {
      "sNo": "4",
      "name": "Tatkal Name and Gender correction in PC / CMM/ Marks Memo",
      "docs": "a) Filled in Form-11. b) Previous certificate where the correction is required. c) Photostat copies of SSC & Aadhaar Card.",
      "amount": "as specified in the application form",
      "downloads": [
        {
          "url": "formdownloads/Form-11.pdf",
          "label": "Form-11"
        }
      ]
    }
  ],
  "online": [
    {
      "sNo": "1",
      "name": "Original Degree Certificate",
      "docs": "Documents to be uploaded a) Photostat copy of PC b) Passport size photograph(for students admitted before 2010)",
      "amount": "In-Convocation: Rs. 600/-  / Pre-Convocation: Rs.\r\n\t\t\t\t3500/- /  Post-Convocation: Rs. 600/- + Late fee of Rs. 500/-\r\n\t\t\t\tper year",
      "downloads": []
    },
    {
      "sNo": "2",
      "name": "Migration certificate",
      "docs": "Select certificates then choose migration certificate option",
      "amount": "Rs. 100/-",
      "downloads": []
    },
    {
      "sNo": "3",
      "name": "Certification of Medium of Instruction",
      "docs": "Select certificates then choose Medium of Instruction certificate option",
      "amount": "Rs. 100/-",
      "downloads": []
    },
    {
      "sNo": "4",
      "name": "Transcripts B.Tech. (Admitted after 1999). B.Pharm, M.Tech, MBA, MCA, M.Pharm (Admitted after 2009)",
      "docs": "Select certificates then choose Transcript Service option",
      "amount": "Rs. 40/- per each copy",
      "downloads": []
    }
  ]
};
